# Generated by Django 3.1.6 on 2021-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Краткое содержание')),
                ('full_text', models.TextField(default='', verbose_name='Полное содержание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
