# Generated by Django 3.1.6 on 2021-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.TextField(null=True, verbose_name='Теги, ключевые слова'),
        ),
    ]
