# Generated by Django 3.1.6 on 2021-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(default='BGMT', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_avatar',
            field=models.ImageField(default='media/bgmt-logo-minimal.png', upload_to='', verbose_name='Фото автора'),
        ),
    ]
