# Generated by Django 3.1.6 on 2021-02-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_avatar',
            field=models.ImageField(default='bgmt-logo-minimal.png', upload_to='', verbose_name='Фото автора'),
        ),
    ]
