# Generated by Django 3.1.6 on 2021-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210227_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_avatar',
            field=models.ImageField(default='bgmt-minimal-logo.png', upload_to='', verbose_name='Фото автора'),
        ),
    ]
