# Generated by Django 3.1.6 on 2021-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210227_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_avatar',
            field=models.ImageField(default='/bgmt-logo-minimal.png', upload_to='', verbose_name='Фото автора'),
        ),
    ]
