# Generated by Django 3.1.6 on 2021-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210301_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_avatar',
            field=models.ImageField(default='/media/bgmt-logo-minimal.png', upload_to='', verbose_name='Фото автора'),
        ),
    ]
